[package]
name                   = "interleave_evenly"
edition.workspace      = true
description            = "Interleave evenly"
version.workspace      = true
repository.workspace   = true
authors.workspace      = true
rust-version.workspace = true
license.workspace      = true

[dependencies]

[lints]
workspace = true

[dev-dependencies]
pretty_assertions = "1.4.0"
