# Recommended by bevy: https://bevyengine.org/learn/book/getting-started/setup/
[target.x86_64-unknown-linux-gnu]
# linker = "clang"
rustflags = [
  "-Clink-arg=-fuse-ld=mold", # Use mold Linker
  "-Ctarget-cpu=native",
]

# [target.aarch64-apple-darwin]
# linker = "clang"
# rustflags = [
#   "-Clink-arg=-fuse-ld=mold", # Use mold Linker
#   "-Ctarget-cpu=native",
# ]

[build]
rustflags = [
  "-C",
  "target-cpu=native",
]
